<?php

namespace App\Filament\Shared\Pages;

use Filament\Pages\Page;
use Illuminate\Database\Eloquent\Model;

class Meals extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.meals';

    public static function getUrl(array $parameters = [], bool $isAbsolute = true, ?string $panel = null, ?Model $tenant = null): string
    {
        return parent::getUrl($parameters, $isAbsolute, $panel, $tenant); // TODO: Change the autogenerated stub
    }
}
